# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca770f99cb9b93477d64f16124233105b1767d945b422e5b00b8520aca2ac0982817dd517e84f1ddd42661c86caa39d14913d8c2ecdeb0a0f9fa965286d6a799

test:
  secret_key_base: b5a46295d95ccb836c06a6221c7637064df57b613fabfd082895ca7734d69c9c9cab038170754b216f20c8abfef39f6ea6cc5ba73b695ee8acb855b0fd23ba20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
